const BASE_URL = "https://gorgeous-turtle-loudly.ngrok-free.app";
const API = {
  'ohlc': `${BASE_URL}/ohlc`,
  'gherkin-query': `${BASE_URL}/gherkin-query`,
  // BASE_URL: 'http://192.168.29.29:5001/api/',
  //BASE_URL: 'https://stage-api.welrm.com/api/',
  // BASE_URL: "https://api.welrm.com/api/",,
  //BASE_URL : 'https://33ba-103-101-213-114.ngrok-free.app/api/',
  COUNT: "user/count",
  SEND_OTP: "user/send-otp",
  OWNER_SEND_OTP: "user/send-otp/owner",
  VERIFY_OTP: "user/verify-otp",
  LOGIN: "login",
  CHANGE_PASSWORD: "user/change-password",
  OWNER_ROOM: "owner/rooms",
  GET_PROFILE: "user/profile",
  GET_OWNER_PROFILE: "owner/profile",
  UPDATE_OWNER_PROFILE: "customer/owner-profile",
  DELETE_HOTEL_IMAGE: "hotel/img/",
  DELETE_HOTEL_ROOM: "hotel/room/",
  REGISTER_HOTEL: "hotel/",
  REGISTER_HOTEL_WITHOUT_TOKEN: "hotel/mupdate",
  COMPLEMENTRY_SERVICE: "hotel/amenities",
  GET_ROOM_TYPE: "option/room_type",
  ADD_ROOM: "hotel/room",
  UPDATE_ROOM: "hotel/room/",
  UPDATE_ROOM_IMAGE: "hotel/room-img/",
  DELETE_ROOM_IMAGE: "hotel/room-img/",
  DASHBOARD: "owner/dashboard",
  ADD_ROOM_TYPE: "option/room-type",
  VERIFY_EMAIL: "user/verify-email/",
  FORGOT_PASSWORD: "forgot-password",
  FORGOT_PASSWORD_VERIFY_OTP: "forgot-password/otp-verify",
  RESET_PASSWORD: "reset-password",
  SEND_MOBILE_OTP: "user/send-mobile-otp",
  VERIFY_MOBILE_OTP: "user/verify-mobile-otp",
  USER_RESET_PASSWORD: "user/reset-password",
  SOCIAL_AUTH: "social-auth",
  USER_NOTIFICATION: "user/notifications",
  USER_NOTIFICATION_CLEAR: "user/notifications/clear",
  USER_NOTIFICATION_SEEN: "user/notifications/seen",

  GET_CUSTOMER_PROFILE: "customer/profile",
  CUSTOMER_PROFILE_UPDATE: "customer/profile",
  CUSTOMER_GET_HOTELS: "customer/hotels",
  CUSTOMER_GET_HOTELS_DETAILS: "customer/hotel/",
  CUSTOMER_ROOMS: "hotel/room/filter/",
  CUSTOMER_BOOK: "booking/room/book",
  CUSTOMER_BOOK_LIST: "booking/list",
  CUSTOMER_BOOK_HISTORY: "booking/history",
  CUSTOMER_BOOK_CANCEL: "booking/cancel/",
  CUSTOMER_RATING: "booking/rating",
  CUSTOMER_COUPON: "user/coupon",
  CUSTOMER_COUPON_APPLY: "user/couponUsed",
  CUSTOMER_ROOM_SOLD_DATE: "hotel/getSoldOut",
  OWNER_BOOK_LIST: "owner/get-pending-bookings",
  OWNER_BOOKED_LIST: "owner/get-confirmed-bookings",
  OWNER_CANCELED_BOOKING_LIST: "owner/get-cancelled-bookings",
  OWNER_CHECKOUT_BOOKING_LIST: "owner/get-checkout-bookings",
  OWNER_BOOK_APPROVE: "booking/confirm/",
  OWNER_BOOK_EXTEND: "booking/extend/",
  OWNER_BOOK_CHECKOUT: "owner/checkout-booking",

  OWNER_SUBSCRIPTIONS: "subscription",
  OWNER_PURCHASE_SUBSCRIPTIONS: "subscription/purchase",
  OWNER_ROOM_SOLD_OUT: "hotel/soldOut",
};

export default API;
